root = "."

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  full_bin = "./tmp/api"
  include_dir = ["cmd", "internal"]
  include_ext = ["go"]
  exclude_dir = ["web", "tmp", "deploy", "db", "scripts"]

[log]
  time = true

[proxy]
  port = 8080
