// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID           uuid.UUID
	Url          string
	Title        string
	Etag         sql.NullString
	LastModified sql.NullString
	LastCrawled  sql.NullTime
	Active       bool
}

type Item struct {
	ID          uuid.UUID
	FeedID      uuid.UUID
	Guid        sql.NullString
	Url         string
	Title       string
	Author      sql.NullString
	ContentHtml string
	ContentText string
	PublishedAt sql.NullTime
	RetrievedAt time.Time
	ContentHash []byte
}
